import {
  ArrowUpRight,
  BadgeCheck,
  BadgePercent,
  CalendarCheck,
  Check,
  ClipboardPen,
  Clock,
  Flower2,
  House,
  Leaf,
  Mail,
  MapPin,
  Menu,
  Phone,
  Scissors,
  ShieldCheck,
  Sprout,
  Sun,
  TreeDeciduous,
  Users,
  X,
} from "@lucide/astro";

/** Ikoner som går att välja i src/site.config.ts. Lägg till fler här vid behov. */
export const icons = {
  arrowUpRight: ArrowUpRight,
  badge: BadgeCheck,
  percent: BadgePercent,
  calendar: CalendarCheck,
  check: Check,
  clipboard: ClipboardPen,
  clock: Clock,
  flower: Flower2,
  house: House,
  leaf: Leaf,
  mail: Mail,
  pin: MapPin,
  menu: Menu,
  phone: Phone,
  scissors: Scissors,
  shield: ShieldCheck,
  sprout: Sprout,
  sun: Sun,
  tree: TreeDeciduous,
  users: Users,
  x: X,
} as const;

export type IconName = keyof typeof icons;
